### ISSUE TITLE
Unresolved dependencies

### ISSUE THREAD

**Issue by Alotor** [hablapps/dontfeartheoptics#4]
I was following the instructions before the workshop and It's not downloading all dependencies. The error is the following.

```
➜  dontfeartheoptics git:(master) ./sbt compile
[info] Loading project definition from /home/alotor/code/courses/dontfeartheoptics/project
[info] Loading settings from build.sbt ...
[info] Set current project to candy (in build file:/home/alotor/code/courses/dontfeartheoptics/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Updating {file:/home/alotor/code/courses/dontfeartheoptics/}dontfeartheoptics...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.github.julien-truffaut#monocle-core_2.12;1.5.0-SNAPSHOT: java.lang.NullPointerException at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.getURLInfo(GigahorseUrlHandler.scala:54)
[warn] 	:: com.github.julien-truffaut#monocle-generic_2.12;1.5.0-SNAPSHOT: java.lang.NullPointerException at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.getURLInfo(GigahorseUrlHandler.scala:54)
[warn] 	:: com.github.julien-truffaut#monocle-macro_2.12;1.5.0-SNAPSHOT: java.lang.NullPointerException at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.getURLInfo(GigahorseUrlHandler.scala:54)
[warn] 	:: com.github.julien-truffaut#monocle-state_2.12;1.5.0-SNAPSHOT: java.lang.NullPointerException at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.getURLInfo(GigahorseUrlHandler.scala:54)
[warn] 	:: com.github.julien-truffaut#monocle-refined_2.12;1.5.0-SNAPSHOT: java.lang.NullPointerException at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.getURLInfo(GigahorseUrlHandler.scala:54)
[warn] 	:: com.github.julien-truffaut#monocle-unsafe_2.12;1.5.0-SNAPSHOT: java.lang.NullPointerException at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.getURLInfo(GigahorseUrlHandler.scala:54)
[warn] 	:: com.github.julien-truffaut#monocle-law_2.12;1.5.0-SNAPSHOT: java.lang.NullPointerException at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.getURLInfo(GigahorseUrlHandler.scala:54)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.github.julien-truffaut:monocle-state_2.12:1.5.0-SNAPSHOT (/home/alotor/code/courses/dontfeartheoptics/build.sbt#L13-26)
[warn] 		  +- org.hablapps:candy_2.12:0.1-SNAPSHOT
[warn] 		com.github.julien-truffaut:monocle-generic_2.12:1.5.0-SNAPSHOT (/home/alotor/code/courses/dontfeartheoptics/build.sbt#L13-26)
[warn] 		  +- org.hablapps:candy_2.12:0.1-SNAPSHOT
[warn] 		com.github.julien-truffaut:monocle-core_2.12:1.5.0-SNAPSHOT (/home/alotor/code/courses/dontfeartheoptics/build.sbt#L13-26)
[warn] 		  +- org.hablapps:candy_2.12:0.1-SNAPSHOT
[warn] 		com.github.julien-truffaut:monocle-macro_2.12:1.5.0-SNAPSHOT (/home/alotor/code/courses/dontfeartheoptics/build.sbt#L13-26)
[warn] 		  +- org.hablapps:candy_2.12:0.1-SNAPSHOT
[warn] 		com.github.julien-truffaut:monocle-unsafe_2.12:1.5.0-SNAPSHOT (/home/alotor/code/courses/dontfeartheoptics/build.sbt#L13-26)
[warn] 		  +- org.hablapps:candy_2.12:0.1-SNAPSHOT
[warn] 		com.github.julien-truffaut:monocle-law_2.12:1.5.0-SNAPSHOT (/home/alotor/code/courses/dontfeartheoptics/build.sbt#L13-26)
[warn] 		  +- org.hablapps:candy_2.12:0.1-SNAPSHOT
[warn] 		com.github.julien-truffaut:monocle-refined_2.12:1.5.0-SNAPSHOT (/home/alotor/code/courses/dontfeartheoptics/build.sbt#L13-26)
[warn] 		  +- org.hablapps:candy_2.12:0.1-SNAPSHOT
```

Maybe is expected but I let you know in case someone else is having this issue :smile: 

Best regards,

**Comment by jeslg** [comment]
Hi @Alotor, we're using our own fork for Monocle (the optic library we'll be using) so the dependencies are in our own server. It shouldn't fail anyway. I'll take a look to see what is going on. Thanks!

**Comment by jeslg** [comment]
It seems that SBT 1.0 is not happy with our resolver, so I've set 0.13 again in https://github.com/hablapps/dontfeartheoptics/commit/2fa1a6e06cee4b7399f05d47d894b882d312fa3f. @Alotor, could you please pull master and check the fix?

**Comment by jeslg** [comment]
I've been informed that it's working nicely now, via [gitter].

**Comment by Alotor** [comment]
Yeah! It's working. :+1: 

See you on the workshop.
